---
- name: Configuration SSH pour autoriser l'authentification par mot de passe
  hosts: all
  become: true
  tasks:

    - name: Forcer PasswordAuthentication à yes dans 60-cloudimg-settings.conf
      ansible.builtin.copy:
        dest: /etc/ssh/sshd_config.d/60-cloudimg-settings.conf
        content: |
          PasswordAuthentication yes
        owner: root
        group: root
        mode: '0644'

    - name: Redémarrer le service SSH pour appliquer les modifications
      ansible.builtin.systemd:
        name: ssh
        state: restarted
